use num_enum::TryFromPrimitive;
use std::convert::TryFrom;
use crate::types::*;

/// Server message opcode. Tells the client what type of operation it should perform.
#[derive(Copy, Clone, Debug, Eq, PartialEq, TryFromPrimitive)]
#[repr(u8)]
pub enum Op {
    /// Client must decrypt received data and send it back in order to log into the
    /// server.
    LoginInfo = '6' as u8,
    /// Client must set some game parameters.
    SetupGame = 'a' as u8,
    
    Angle1 = 'e' as u8,
    Angle2 = 'E' as u8,
    Angle3 = '3' as u8,
    Angle4 = '4' as u8,
    Angle5 = '5' as u8,

    /// Player died and connection will soon be closed.
    GameOver = 'v' as u8,
    /// A snake must update its fullness value.
    UpdateFullness = 'h' as u8,
    /// A new snake must be loaded or an existing snake must be removed.
    SnakeAction = 's' as u8,
    /// Response to client ping
    PingResponse = 'p' as u8,
    /// The minimap must be updated.
    UpdateMinimap = 'u' as u8,
    /// A snake must be moved to a new location.
    PosAbs = 'g' as u8,
    /// A snake must be moved to a new location and a new section must be added.
    GrowAbs = 'n' as u8,
    /// A snake must be displaced by an offset.
    PosRel = 'G' as u8,
    /// A snake must be displaced by an offset and a new section must be added.
    GrowRel = 'N' as u8,
    /// Game stats must be updated.
    UpdateStats = 'l' as u8,
    /// A snake must lose a section.
    Shrink = 'r' as u8,
    /// Unload all food within a sector.
    RemoveSectorFood = 'w' as u8,
    /// Load all food within a sector.
    LoadSectorFood = 'F' as u8,
    /// Load a single food generated by boost exhaust or by snake death.
    SnakeFood = 'b' as u8,
    /// Load a single food spawned naturally.
    SpawnFood = 'f' as u8,
    /// Unload a single food that has just been eaten.
    EatFood = 'c' as u8,
    /// Updates the state of a prey.
    UpdatePrey = 'j' as u8,
    /// Loads or unloads a prey.
    PreyAction = 'y' as u8,
}

pub type ClientMsg = Vec<u8>;

/// A server message sent to the client. Contains additional data to help parsing data.
pub struct ServerMsg {
    /// The message raw data, in bytes.
    data: Vec<u8>,
    /// The message's cursor, where the data is read.
    i: usize,
}

impl ServerMsg {
    /// The index of the first byte of the message's payload.
    const START: usize = 3;

    /// Creates a new message from the given data.
    pub fn new(data: Vec<u8>) -> Self {
        debug_assert!(Self::START <= data.len());
        Self {
            data,
            i: Self::START,
        }
    }

    /// Returns the opcode of the message.
    pub fn opcode(&self) -> Result<Op, char> {
        match Op::try_from(self.data[2]) {
            Ok(op) => Ok(op),
            Err(_) => Err(self.data[2] as char),
        }
    }

    /// Returns the length of the message.
    pub fn len(&self) -> usize  {
        self.data.len()
    }

    /// Returns a slice of the message's payload.
    pub fn payload(&self) -> &[u8] {
        &self.data[Self::START..]
    }

    /// Returns the cursor position.
    pub fn pos(&self) -> usize {
        self.i
    }

    /// Moves the current position to the given position.
    pub fn go_to(&mut self, pos: usize) {
        self.i = pos;
        debug_assert!(self.i < self.data.len());
    }

    /// Rewinds the message to the starting position.
    pub fn rewind(&mut self) {
        self.i = Self::START;
    }

    /// Skips the given number of bytes.
    pub fn skip(&mut self, count: usize) {
        self.i += count;
        debug_assert!(self.i < self.data.len());
    }

    pub fn has_reached_end(&self) -> bool {
        self.i >= self.data.len()
    }

    /// Returns 1 byte of message data and moves the cursor.
    pub fn read_u8(&mut self) -> u8 {
        let result = self.data[self.i];
        self.i += 1;
        debug_assert!(self.i <= self.data.len());
        result
    }

    /// Returns 2 bytes of message data and moves the cursor.
    pub fn read_u16(&mut self) -> u16 {
        let result = 
            (self.data[self.i] as u16) << 8 
            | self.data[self.i + 1] as u16;

        self.i += 2;
        debug_assert!(self.i <= self.data.len());
        result
    }

    /// Returns 3 byte of message data and moves the cursor.
    pub fn read_u24(&mut self) -> u32 {
        let result =
            (self.data[self.i] as u32) << 16 
            | (self.data[self.i + 1] as u32) << 8 
            | self.data[self.i + 2] as u32;
        
        self.i += 3;
        debug_assert!(self.i <= self.data.len());
        result
    }

    pub fn read_string(&mut self) -> String {
        let length = self.read_u8() as usize;
        let slice = &self.data[self.i .. self.i + length];
        let result = match std::str::from_utf8(slice) {
            Ok(str) => str.to_owned(),
            Err(_) => "".to_owned(),
        };

        self.i += length;
        result
    }

    pub fn read_id(&mut self) -> Id {
        self.read_u16()
    }

    /// Returns a `Pos` component, reading 6 bytes from the message.
    pub fn read_pos_6_bytes(&mut self) -> Pos {
        Pos::new(
            self.read_u24() as f32 / 5.0,
            self.read_u24() as f32 / 5.0,
        )
    }

    /// Returns a `Pos` component, reading 4 bytes from the message.
    pub fn read_pos_4_bytes(&mut self) -> Pos {
        Pos::new(
            self.read_u16() as f32,
            self.read_u16() as f32,
        )
    }

    /// Returns a `Pos` component, meant to be used as a delta, reading 2 bytes from
    /// the message.
    pub fn read_pos_delta(&mut self) -> Pos {
        Pos::new(
            self.read_u8() as f32 - 128.0,
            self.read_u8() as f32 - 128.0,
        )
    }

    pub fn read_pos_delta_half(&mut self) -> Pos {
        Pos::new(
            (self.read_u8() as i32 - 127) as f32 / 2.0,
            (self.read_u8() as i32 - 127) as f32 / 2.0,
        )
    }

    pub fn read_prey_pos(&mut self) -> Pos {
        Pos::new(
            1.0 + 3.0 * self.read_u16() as f32,
            1.0 + 3.0 * self.read_u16() as f32,
        )
    }

    pub fn read_body(&mut self, fullness: Fullness) -> Body {
        // TODO: Rewrite idiomatically
        let mut section_pos = Pos::new(0.0, 0.0);
        let mut body = Body::new();
        body.fullness = fullness;
        let mut first = true;
        while !self.has_reached_end() {
            if first {
                first = false;
                section_pos = self.read_pos_6_bytes();
            } else {
                section_pos += self.read_pos_delta_half();
            }
            body.add_point(section_pos);
        }

        body
    }

    /// Returns a `Fullness` type, reading 3 bytes from the message.
    pub fn read_fullness(&mut self) -> Fullness {
        self.read_u24() as f32 / 16777215.0
    }

    /// Returns a `Size` type, reading 1 byte from the message.
    pub fn read_size(&mut self) -> Size {
        self.read_u8() as f32 / 5.0
    }

    pub fn read_direction(&mut self) -> Direction {
        match self.read_u8() as i32 - 48 {
            0 => Direction::None,
            1 => Direction::Left,
            2 => Direction::Right,
            _ => unreachable!(),
        }
    }

    pub fn read_angle(&mut self) -> f32 {
        2.0 * self.read_u24() as f32 * std::f32::consts::PI / 16777215.0
    }

    pub fn read_angle_short(&mut self) -> f32 {
        2.0 * self.read_u8() as f32 * std::f32::consts::PI / 256.0
    }

    pub fn read_speed(&mut self) -> f32 {
        self.read_u16() as f32 / 1000.0
    }

    pub fn read_speed_short(&mut self) -> f32 {
        self.read_u8() as f32 / 18.0
    }
}

impl IntoIterator for ServerMsg {
    type Item = u8;
    type IntoIter = std::vec::IntoIter<Self::Item>;

    fn into_iter(self) -> Self::IntoIter {
        self.data.into_iter()
    }
}

/// Tracks connection state between client and server.
#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum ConnectionState {
    /// Client is logging into the server.
    LoggingIn,
    /// Client is logged in and can send gameplay input.
    Playing,
    /// Connection has been interrupted by client or server.
    Disconnected,
    /// There is no client-server communication. The client only receives server
    /// messages.
    Unilateral,
}

/// The implementor of this trait is something that streams messages to the user code
/// and forwards messages to a third party (a server, for example).
pub trait Connection {
    fn poll_messages(&mut self) -> Vec<ServerMsg>;
    fn send(&mut self, _message: ClientMsg) {}
    fn close(&mut self) {}
    fn state(&self) -> ConnectionState;
    fn set_state(&mut self, _state: ConnectionState) {}
    fn url(&self) -> String { "".to_owned() }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn read_u8() {
        let mut m = ServerMsg::new(vec![23, 5, 9, 78]);
        let result = m.read_u8();
        assert_eq!(result, 78u8);
    }

    #[test]
    fn read_u16() {
        let mut m = ServerMsg::new(vec![23, 5, 9, 78, 92]);
        let result = m.read_u16();
        assert_eq!(result, 20060u16);
    }

    #[test]
    fn read_u24() {
        let mut m = ServerMsg::new(vec![23, 5, 9, 78, 92, 235, 255, 36]);
        let result = m.read_u24();
        assert_eq!(result, 5135595u32);
    }

    #[test]
    fn read_string() {
        let mut m = ServerMsg::new(vec![0, 0, 0, 5, 72, 101, 108, 108, 111, 255]);
        let result = m.read_string();
        assert_eq!(result, String::from("Hello"));
        assert_eq!(m.read_u8(), 255);
    }

    #[test]
    fn read_string_zero_length() {
        let mut m = ServerMsg::new(vec![0, 0, 0, 0, 72, 101, 108, 108, 111, 255]);
        let result = m.read_string();
        assert_eq!(result, String::from(""));
        assert_eq!(m.read_u8(), 72);
    }
}